server:
  port: 8803
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #再次配置需要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用户binding的整合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq相关的环境变量
            spring:
              rabbitmq:
                host: myrabbitmq.com
                port: 5672
                username: guest
                password: guest
      bindings: #服务整合
        input: #这是一个通道的名称
          destination: studyExchange #表示要使用的Exchange名称的定义
          content-type: application/json #设置消息类型
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          group: groupA

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 5 #如果超过这个时间
    instance-id: receive-8803.com #在信息列表显示主机名称
    prefer-ip-address: true #访问路径变为IP地址