server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: qcb
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qin.springcloud.entities #所有Entity别名所在包

eureka:
  client:
    # 将当前服务注册到eureka服务
    register-with-eureka: true
    # 从euraka服务端拉取注册的服务信息
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka