server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态路由的功能，根据服务名进行路由
      routes:
        - id: payment_routh  #路由ID，要求唯一
          uri: http://localhost:8001  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**    #断言，路径相匹配的进行路由
        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/discovery
        - id: payment_routh3
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/feign/timeout

eureka:
  client:
    # 将当前服务注册到eureka服务
    register-with-eureka: true
    # 从euraka服务端拉取注册的服务信息
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka